import { CSSRule } from "@/types/CSSRules";
export declare const fluid: CSSRule;
export declare const grid: CSSRule;
export declare const noGrow: CSSRule;
export declare const grid1: CSSRule;
export declare const grid2: CSSRule;
export declare const grid3: CSSRule;
export declare const grid4: CSSRule;
export declare const grid5: CSSRule;
export declare const grid6: CSSRule;
export declare const grid7: CSSRule;
export declare const grid8: CSSRule;
export declare const grid9: CSSRule;
export declare const grid10: CSSRule;
export declare const grid11: CSSRule;
export declare const grid12: CSSRule;
export declare const absolute: CSSRule;
export declare const mb1: CSSRule;
export declare const mb2: CSSRule;
export declare const mb3: CSSRule;
export declare const mb4: CSSRule;
export declare const mb5: CSSRule;
export declare const mb6: CSSRule;
export declare const mb7: CSSRule;
export declare const mb8: CSSRule;
declare const alignSelf: {
    fluid: string;
    noGrow: string;
    grid: string;
    grid1: string;
    grid2: string;
    grid3: string;
    grid4: string;
    grid5: string;
    grid6: string;
    grid7: string;
    grid8: string;
    grid9: string;
    grid10: string;
    grid11: string;
    grid12: string;
    absolute: string;
    mb1: string;
    mb2: string;
    mb3: string;
    mb4: string;
    mb5: string;
    mb6: string;
    mb7: string;
    mb8: string;
};
export default alignSelf;
