import { HeadingCSSRule } from "@/types/CSSRules";
export declare const bold = "font-weight: bold;";
export declare const textCenter = "text-align:center;";
export declare const h10: HeadingCSSRule<10>;
export declare const h12: HeadingCSSRule<12>;
export declare const h14: HeadingCSSRule<14>;
export declare const h16: HeadingCSSRule<16>;
export declare const h18: HeadingCSSRule<18>;
export declare const h22: HeadingCSSRule<22>;
export declare const h32: HeadingCSSRule<32>;
export declare const h42: HeadingCSSRule<42>;
declare const typo: {
    bold: string;
    textCenter: string;
    h10: "font-size: 10px; line-height: 1.2;";
    h12: "font-size: 12px; line-height: 1.3;";
    h14: "font-size: 14px; line-height: 1.4;";
    h16: "font-size: 16px; line-height: 1.3;";
    h18: "font-size: 18px; line-height: 1.3;";
    h22: "font-size: 22px; line-height: 1.2;";
    h32: "font-size: 32px; line-height: 1.1;";
    h42: "font-size: 42px; line-height: 1.1;";
};
export default typo;
